# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - ci
    - azure-pipelines
  paths:
    exclude:
    - guide/

pr:
- master

strategy:
  matrix:
    vs2017-win2016:
      IMAGE_NAME: 'vs2017-win2016'
    windows-2019:
      IMAGE_NAME: 'windows-2019'

    macos-10.14-emacs-25.3:
      IMAGE_NAME: 'macos-10.14'
      EVM_EMACS: emacs-25.3
    macos-10.14-emacs-26.3:
      IMAGE_NAME: 'macos-10.14'
      EVM_EMACS: emacs-26.3
    macos-10.14-emacs-27.1:
      IMAGE_NAME: 'macos-10.14'
      EVM_EMACS: emacs-27.1

    # Emacs is getting "Killed 9" on these agents, probably due to macOS 10.15 updates.
    # macos-10.15-emacs-25.3:
    #   IMAGE_NAME: 'macos-10.15'
    #   EVM_EMACS: emacs-25.3
    # macos-10.15-emacs-26.3:
    #   IMAGE_NAME: 'macos-10.15'
    #   EVM_EMACS: emacs-26.3
    macos-10.15-emacs-27.1:
      IMAGE_NAME: 'macos-10.15'
      EVM_EMACS: emacs-27.1

    # thread 'main' panicked at '`libclang` function not loaded: `clang_createIndex`. This crate requires that `libclang` 3.9 or later be installed on your system. For more information on how to accomplish this, see here: https://rust-lang.github.io/rust-bindgen/requirements.html#installing-clang-39', /home/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.2.0/src/lib.rs:1682:1
    # ubuntu-16.04-emacs-25.3:
    #   IMAGE_NAME: 'ubuntu-16.04'
    #   EVM_EMACS: emacs-25.3
    # ubuntu-16.04-emacs-27.1:
    #   IMAGE_NAME: 'ubuntu-16.04'
    #   EVM_EMACS: emacs-27.1

    # https://github.com/ubolonton/emacs-module-rs/issues/1#issuecomment-476049325
    # ubuntu-16.04-emacs-26.3:
    #   IMAGE_NAME: 'ubuntu-16.04'
    #   EVM_EMACS: emacs-26.3

    ubuntu-18.04-emacs-25.3:
      IMAGE_NAME: 'ubuntu-18.04'
      EVM_EMACS: emacs-25.3
    ubuntu-18.04-emacs-26.3:
      IMAGE_NAME: 'ubuntu-18.04'
      EVM_EMACS: emacs-26.3
    ubuntu-18.04-emacs-27.1:
      IMAGE_NAME: 'ubuntu-18.04'
      EVM_EMACS: emacs-27.1

pool:
  vmImage: $(IMAGE_NAME)

steps:
- template: steps/setup-rust.yml
  parameters:
    version: '1.56.0'
- template: steps/-build.yml
- template: steps/setup-emacs.yml
- template: steps/-test.yml
